services:
  - type: web
    name: UDON_shindan
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: UDONshindan
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: UDONshindan
    databaseName: udonshindan
    user: UDON_shindan
    region: singapore
    